import { NextResponse } from "next/server";
import { z } from "zod";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const transactionSchema = z.object({
  amount: z.coerce.number().positive(),
  type: z.enum(["INCOME", "EXPENSE"]),
  description: z.string().min(1).max(200),
  date: z.string(),
  categoryId: z.string().optional(),
});

export async function POST(request: Request) {
  try {
    const session = await auth();

    if (!session?.user?.id) {
      return NextResponse.json(
        { message: "Unauthorized" },
        { status: 401 }
      );
    }

    const body = await request.json();

    const result = transactionSchema.safeParse(body);

    if (!result.success) {
      return NextResponse.json(
        { message: "Invalid transaction data" },
        { status: 400 }
      );
    }

    const {
      amount,
      type,
      description,
      date,
      categoryId,
    } = result.data;

    // Verify that the selected category belongs
    // to the currently logged-in user and matches
    // the transaction type.
    if (categoryId) {
      const category = await prisma.category.findFirst({
        where: {
          id: categoryId,
          userId: session.user.id,
          type,
        },
      });

      if (!category) {
        return NextResponse.json(
          {
            message:
              "Invalid category for this transaction type",
          },
          { status: 400 }
        );
      }
    }

    // Create the transaction.
    //
    // createdAt is automatically generated by Prisma.
    // We use createdAt for sorting so the newest
    // created transaction always appears first.
    const transaction =
      await prisma.transaction.create({
        data: {
          amount,
          type,
          description,
          date: new Date(date),
          userId: session.user.id,
          categoryId: categoryId || null,
        },
        include: {
          category: true,
        },
      });

    // Return the complete transaction directly.
    return NextResponse.json(
      transaction,
      { status: 201 }
    );
  } catch (error) {
    console.error(
      "Transaction creation error:",
      error
    );

    return NextResponse.json(
      { message: "Something went wrong" },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const session = await auth();

    if (!session?.user?.id) {
      return NextResponse.json(
        { message: "Unauthorized" },
        { status: 401 }
      );
    }

    const transactions =
      await prisma.transaction.findMany({
        where: {
          userId: session.user.id,
        },

        include: {
          category: true,
        },

        // IMPORTANT:
        // Sort by creation time, not transaction date.
        //
        // This guarantees that the most recently
        // created transaction appears first even if
        // its transaction date is older.
        orderBy: {
          createdAt: "desc",
        },
      });

    return NextResponse.json(
      transactions
    );
  } catch (error) {
    console.error(
      "Transaction fetch error:",
      error
    );

    return NextResponse.json(
      { message: "Something went wrong" },
      { status: 500 }
    );
  }
}